spring:
  application:
    name: quote-service

#server:
#  port: 8088

eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: https://eureka-service-unassuageable-unkindliness.cfapps.io/eureka/